export enum ServiciosSistema {
  AUTENTICACION = 'AUTENTICACION',
  CONDUCTORES = 'CONDUCTORES',
  VIAJES = 'VIAJES',
  PASAJEROS = 'PASAJEROS',
  PAGOS = 'PAGOS',
  CALIFICACIONES = 'CALIFICACIONES',
  CONFIGURACION = 'CONFIGURACION',
}
